#############################################################################
# Makefile for building: emindappstore
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  emindappstore.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile emindappstore.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/packagekitqt5/PackageKit -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = emindappstore1.0.0
DISTDIR = /home/yin/work/temp/emindappstore/.tmp/emindappstore1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 /usr/lib/x86_64-linux-gnu/libpackagekitqt5.so -lQt5QuickWidgets -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		softwarecenterwindow.cpp \
		homewidget.cpp \
		titlebar.cpp \
		ClassAndMorePage/classtop.cpp \
		ClassAndMorePage/classwidget.cpp \
		ClassAndMorePage/element.cpp \
		ClassAndMorePage/showmore.cpp \
		updatepage/appwidget.cpp \
		updatepage/funcwidget.cpp \
		updatepage/taskbar.cpp \
		detailwidget.cpp \
		customlineedit.cpp \
		searchwidget.cpp \
		datamanager.cpp \
		imgwindow.cpp \
		ClassAndMorePage/classpage.cpp \
		ClassAndMorePage/morepage.cpp \
		ClassAndMorePage/recommendwidget.cpp \
		managerpage/managerpage.cpp \
		managerpage/managerwidget.cpp \
		updatepage/pkupdates.cpp \
		updatepage/updatepage.cpp \
		jsonfunc.cpp \
		guifactory.cpp \
		commentlistmodel.cpp \
		homeimglistmodel.cpp \
		detailimglistmodel.cpp qrc_style.cpp \
		qrc_qml.cpp \
		qrc_image.cpp \
		moc_softwarecenterwindow.cpp \
		moc_homewidget.cpp \
		moc_titlebar.cpp \
		moc_classtop.cpp \
		moc_classwidget.cpp \
		moc_element.cpp \
		moc_showmore.cpp \
		moc_appwidget.cpp \
		moc_funcwidget.cpp \
		moc_taskbar.cpp \
		moc_detailwidget.cpp \
		moc_customlineedit.cpp \
		moc_searchwidget.cpp \
		moc_datamanager.cpp \
		moc_imgwindow.cpp \
		moc_classpage.cpp \
		moc_morepage.cpp \
		moc_recommendwidget.cpp \
		moc_managerpage.cpp \
		moc_managerwidget.cpp \
		moc_pkupdates.cpp \
		moc_updatepage.cpp \
		moc_jsonfunc.cpp \
		moc_qreplytimeout.cpp \
		moc_guifactory.cpp \
		moc_commentlistmodel.cpp \
		moc_homeimglistmodel.cpp \
		moc_detailimglistmodel.cpp
OBJECTS       = main.o \
		softwarecenterwindow.o \
		homewidget.o \
		titlebar.o \
		classtop.o \
		classwidget.o \
		element.o \
		showmore.o \
		appwidget.o \
		funcwidget.o \
		taskbar.o \
		detailwidget.o \
		customlineedit.o \
		searchwidget.o \
		datamanager.o \
		imgwindow.o \
		classpage.o \
		morepage.o \
		recommendwidget.o \
		managerpage.o \
		managerwidget.o \
		pkupdates.o \
		updatepage.o \
		jsonfunc.o \
		guifactory.o \
		commentlistmodel.o \
		homeimglistmodel.o \
		detailimglistmodel.o \
		qrc_style.o \
		qrc_qml.o \
		qrc_image.o \
		moc_softwarecenterwindow.o \
		moc_homewidget.o \
		moc_titlebar.o \
		moc_classtop.o \
		moc_classwidget.o \
		moc_element.o \
		moc_showmore.o \
		moc_appwidget.o \
		moc_funcwidget.o \
		moc_taskbar.o \
		moc_detailwidget.o \
		moc_customlineedit.o \
		moc_searchwidget.o \
		moc_datamanager.o \
		moc_imgwindow.o \
		moc_classpage.o \
		moc_morepage.o \
		moc_recommendwidget.o \
		moc_managerpage.o \
		moc_managerwidget.o \
		moc_pkupdates.o \
		moc_updatepage.o \
		moc_jsonfunc.o \
		moc_qreplytimeout.o \
		moc_guifactory.o \
		moc_commentlistmodel.o \
		moc_homeimglistmodel.o \
		moc_detailimglistmodel.o
DIST          = style.qss \
		updatepage/image/head.png \
		updatepage/image/hide.png \
		README.md \
		app_zh.ts \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		emindappstore.pro softwarecenterwindow.h \
		homewidget.h \
		titlebar.h \
		ClassAndMorePage/classtop.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/showmore.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h \
		updatepage/taskbar.h \
		detailwidget.h \
		customlineedit.h \
		searchwidget.h \
		datamanager.h \
		imgwindow.h \
		ClassAndMorePage/classpage.h \
		ClassAndMorePage/morepage.h \
		ClassAndMorePage/recommendwidget.h \
		managerpage/managerpage.h \
		managerpage/managerwidget.h \
		updatepage/pkupdates.h \
		updatepage/updatepage.h \
		jsonfunc.h \
		qreplytimeout.h \
		sharedata.h \
		guifactory.h \
		commentlistmodel.h \
		homeimglistmodel.h \
		detailimglistmodel.h main.cpp \
		softwarecenterwindow.cpp \
		homewidget.cpp \
		titlebar.cpp \
		ClassAndMorePage/classtop.cpp \
		ClassAndMorePage/classwidget.cpp \
		ClassAndMorePage/element.cpp \
		ClassAndMorePage/showmore.cpp \
		updatepage/appwidget.cpp \
		updatepage/funcwidget.cpp \
		updatepage/taskbar.cpp \
		detailwidget.cpp \
		customlineedit.cpp \
		searchwidget.cpp \
		datamanager.cpp \
		imgwindow.cpp \
		ClassAndMorePage/classpage.cpp \
		ClassAndMorePage/morepage.cpp \
		ClassAndMorePage/recommendwidget.cpp \
		managerpage/managerpage.cpp \
		managerpage/managerwidget.cpp \
		updatepage/pkupdates.cpp \
		updatepage/updatepage.cpp \
		jsonfunc.cpp \
		guifactory.cpp \
		commentlistmodel.cpp \
		homeimglistmodel.cpp \
		detailimglistmodel.cpp
QMAKE_TARGET  = emindappstore
DESTDIR       = 
TARGET        = emindappstore


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: emindappstore.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		emindappstore.pro \
		style.qrc \
		qml.qrc \
		image.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Quick.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Qml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
emindappstore.pro:
style.qrc:
qml.qrc:
image.qrc:
/usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Quick.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Qml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile emindappstore.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents style.qrc qml.qrc image.qrc $(DISTDIR)/
	$(COPY_FILE) --parents softwarecenterwindow.h homewidget.h titlebar.h ClassAndMorePage/classtop.h ClassAndMorePage/classwidget.h ClassAndMorePage/element.h ClassAndMorePage/showmore.h updatepage/appwidget.h updatepage/funcwidget.h updatepage/taskbar.h detailwidget.h customlineedit.h searchwidget.h datamanager.h imgwindow.h ClassAndMorePage/classpage.h ClassAndMorePage/morepage.h ClassAndMorePage/recommendwidget.h managerpage/managerpage.h managerpage/managerwidget.h updatepage/pkupdates.h updatepage/updatepage.h jsonfunc.h qreplytimeout.h sharedata.h guifactory.h commentlistmodel.h homeimglistmodel.h detailimglistmodel.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp softwarecenterwindow.cpp homewidget.cpp titlebar.cpp ClassAndMorePage/classtop.cpp ClassAndMorePage/classwidget.cpp ClassAndMorePage/element.cpp ClassAndMorePage/showmore.cpp updatepage/appwidget.cpp updatepage/funcwidget.cpp updatepage/taskbar.cpp detailwidget.cpp customlineedit.cpp searchwidget.cpp datamanager.cpp imgwindow.cpp ClassAndMorePage/classpage.cpp ClassAndMorePage/morepage.cpp ClassAndMorePage/recommendwidget.cpp managerpage/managerpage.cpp managerpage/managerwidget.cpp updatepage/pkupdates.cpp updatepage/updatepage.cpp jsonfunc.cpp guifactory.cpp commentlistmodel.cpp homeimglistmodel.cpp detailimglistmodel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents app_zh.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp qrc_qml.cpp qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp qrc_qml.cpp qrc_image.cpp
qrc_style.cpp: style.qrc \
		style.qss
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name style style.qrc -o qrc_style.cpp

qrc_qml.cpp: qml.qrc \
		app_zh.qm \
		Imgboxer.qml \
		Comment.qml \
		Imgbox.qml \
		httpData.js \
		ImgDelegate.qml
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_image.cpp: image.qrc \
		image/forward_black.png \
		image/star_100.png \
		image/refresh_black.png \
		image/test3.jpg \
		image/return_black.png \
		image/test2.jpg \
		image/Tux.png \
		image/refresh_gray.png \
		image/search.png \
		image/test1.jpg \
		image/hide.png \
		image/more.png \
		image/star_50.png \
		image/forward_gray.png \
		image/star_0.png \
		image/return_gray.png \
		image/test4.jpg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_moc_header_make_all: moc_softwarecenterwindow.cpp moc_homewidget.cpp moc_titlebar.cpp moc_classtop.cpp moc_classwidget.cpp moc_element.cpp moc_showmore.cpp moc_appwidget.cpp moc_funcwidget.cpp moc_taskbar.cpp moc_detailwidget.cpp moc_customlineedit.cpp moc_searchwidget.cpp moc_datamanager.cpp moc_imgwindow.cpp moc_classpage.cpp moc_morepage.cpp moc_recommendwidget.cpp moc_managerpage.cpp moc_managerwidget.cpp moc_pkupdates.cpp moc_updatepage.cpp moc_jsonfunc.cpp moc_qreplytimeout.cpp moc_guifactory.cpp moc_commentlistmodel.cpp moc_homeimglistmodel.cpp moc_detailimglistmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_softwarecenterwindow.cpp moc_homewidget.cpp moc_titlebar.cpp moc_classtop.cpp moc_classwidget.cpp moc_element.cpp moc_showmore.cpp moc_appwidget.cpp moc_funcwidget.cpp moc_taskbar.cpp moc_detailwidget.cpp moc_customlineedit.cpp moc_searchwidget.cpp moc_datamanager.cpp moc_imgwindow.cpp moc_classpage.cpp moc_morepage.cpp moc_recommendwidget.cpp moc_managerpage.cpp moc_managerwidget.cpp moc_pkupdates.cpp moc_updatepage.cpp moc_jsonfunc.cpp moc_qreplytimeout.cpp moc_guifactory.cpp moc_commentlistmodel.cpp moc_homeimglistmodel.cpp moc_detailimglistmodel.cpp
moc_softwarecenterwindow.cpp: jsonfunc.h \
		sharedata.h \
		softwarecenterwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include softwarecenterwindow.h -o moc_softwarecenterwindow.cpp

moc_homewidget.cpp: homewidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include homewidget.h -o moc_homewidget.cpp

moc_titlebar.cpp: customlineedit.h \
		titlebar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include titlebar.h -o moc_titlebar.cpp

moc_classtop.cpp: ClassAndMorePage/classtop.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/classtop.h -o moc_classtop.cpp

moc_classwidget.cpp: ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/classwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/classwidget.h -o moc_classwidget.cpp

moc_element.cpp: ClassAndMorePage/element.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/element.h -o moc_element.cpp

moc_showmore.cpp: ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/showmore.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/showmore.h -o moc_showmore.cpp

moc_appwidget.cpp: updatepage/appwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatepage/appwidget.h -o moc_appwidget.cpp

moc_funcwidget.cpp: updatepage/funcwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatepage/funcwidget.h -o moc_funcwidget.cpp

moc_taskbar.cpp: updatepage/taskbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatepage/taskbar.h -o moc_taskbar.cpp

moc_detailwidget.cpp: detailwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include detailwidget.h -o moc_detailwidget.cpp

moc_customlineedit.cpp: customlineedit.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include customlineedit.h -o moc_customlineedit.cpp

moc_searchwidget.cpp: ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		searchwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include searchwidget.h -o moc_searchwidget.cpp

moc_datamanager.cpp: datamanager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include datamanager.h -o moc_datamanager.cpp

moc_imgwindow.cpp: imgwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include imgwindow.h -o moc_imgwindow.cpp

moc_classpage.cpp: ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/morepage.h \
		ClassAndMorePage/showmore.h \
		ClassAndMorePage/classpage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/classpage.h -o moc_classpage.cpp

moc_morepage.cpp: ClassAndMorePage/showmore.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/morepage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/morepage.h -o moc_morepage.cpp

moc_recommendwidget.cpp: ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/recommendwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ClassAndMorePage/recommendwidget.h -o moc_recommendwidget.cpp

moc_managerpage.cpp: updatepage/taskbar.h \
		managerpage/managerwidget.h \
		jsonfunc.h \
		sharedata.h \
		updatepage/pkupdates.h \
		updatepage/updatepage.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h \
		managerpage/managerpage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include managerpage/managerpage.h -o moc_managerpage.cpp

moc_managerwidget.cpp: jsonfunc.h \
		sharedata.h \
		managerpage/managerwidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include managerpage/managerwidget.h -o moc_managerwidget.cpp

moc_pkupdates.cpp: jsonfunc.h \
		sharedata.h \
		updatepage/pkupdates.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatepage/pkupdates.h -o moc_pkupdates.cpp

moc_updatepage.cpp: updatepage/taskbar.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h \
		updatepage/pkupdates.h \
		jsonfunc.h \
		sharedata.h \
		updatepage/updatepage.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include updatepage/updatepage.h -o moc_updatepage.cpp

moc_jsonfunc.cpp: sharedata.h \
		jsonfunc.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include jsonfunc.h -o moc_jsonfunc.cpp

moc_qreplytimeout.cpp: qreplytimeout.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include qreplytimeout.h -o moc_qreplytimeout.cpp

moc_guifactory.cpp: guifactory.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include guifactory.h -o moc_guifactory.cpp

moc_commentlistmodel.cpp: commentlistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include commentlistmodel.h -o moc_commentlistmodel.cpp

moc_homeimglistmodel.cpp: homeimglistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include homeimglistmodel.h -o moc_homeimglistmodel.cpp

moc_detailimglistmodel.cpp: detailimglistmodel.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/yin/work/temp/emindappstore -I/usr/include/packagekitqt5/PackageKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include detailimglistmodel.h -o moc_detailimglistmodel.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp softwarecenterwindow.h \
		jsonfunc.h \
		sharedata.h \
		datamanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

softwarecenterwindow.o: softwarecenterwindow.cpp softwarecenterwindow.h \
		jsonfunc.h \
		sharedata.h \
		titlebar.h \
		customlineedit.h \
		homewidget.h \
		searchwidget.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		detailwidget.h \
		ClassAndMorePage/classpage.h \
		ClassAndMorePage/morepage.h \
		ClassAndMorePage/showmore.h \
		managerpage/managerpage.h \
		updatepage/taskbar.h \
		managerpage/managerwidget.h \
		updatepage/pkupdates.h \
		updatepage/updatepage.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h \
		ClassAndMorePage/recommendwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o softwarecenterwindow.o softwarecenterwindow.cpp

homewidget.o: homewidget.cpp homewidget.h \
		ClassAndMorePage/recommendwidget.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homewidget.o homewidget.cpp

titlebar.o: titlebar.cpp titlebar.h \
		customlineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o titlebar.o titlebar.cpp

classtop.o: ClassAndMorePage/classtop.cpp ClassAndMorePage/classtop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classtop.o ClassAndMorePage/classtop.cpp

classwidget.o: ClassAndMorePage/classwidget.cpp ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classwidget.o ClassAndMorePage/classwidget.cpp

element.o: ClassAndMorePage/element.cpp ClassAndMorePage/element.h \
		qreplytimeout.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o ClassAndMorePage/element.cpp

showmore.o: ClassAndMorePage/showmore.cpp ClassAndMorePage/showmore.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o showmore.o ClassAndMorePage/showmore.cpp

appwidget.o: updatepage/appwidget.cpp updatepage/appwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appwidget.o updatepage/appwidget.cpp

funcwidget.o: updatepage/funcwidget.cpp updatepage/funcwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o funcwidget.o updatepage/funcwidget.cpp

taskbar.o: updatepage/taskbar.cpp updatepage/taskbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskbar.o updatepage/taskbar.cpp

detailwidget.o: detailwidget.cpp detailwidget.h \
		sharedata.h \
		jsonfunc.h \
		commentlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detailwidget.o detailwidget.cpp

customlineedit.o: customlineedit.cpp customlineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customlineedit.o customlineedit.cpp

searchwidget.o: searchwidget.cpp searchwidget.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchwidget.o searchwidget.cpp

datamanager.o: datamanager.cpp datamanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datamanager.o datamanager.cpp

imgwindow.o: imgwindow.cpp imgwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgwindow.o imgwindow.cpp

classpage.o: ClassAndMorePage/classpage.cpp ClassAndMorePage/classpage.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h \
		ClassAndMorePage/morepage.h \
		ClassAndMorePage/showmore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classpage.o ClassAndMorePage/classpage.cpp

morepage.o: ClassAndMorePage/morepage.cpp ClassAndMorePage/morepage.h \
		ClassAndMorePage/showmore.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o morepage.o ClassAndMorePage/morepage.cpp

recommendwidget.o: ClassAndMorePage/recommendwidget.cpp ClassAndMorePage/recommendwidget.h \
		ClassAndMorePage/classwidget.h \
		ClassAndMorePage/element.h \
		ClassAndMorePage/classtop.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recommendwidget.o ClassAndMorePage/recommendwidget.cpp

managerpage.o: managerpage/managerpage.cpp managerpage/managerpage.h \
		updatepage/taskbar.h \
		managerpage/managerwidget.h \
		jsonfunc.h \
		sharedata.h \
		updatepage/pkupdates.h \
		updatepage/updatepage.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managerpage.o managerpage/managerpage.cpp

managerwidget.o: managerpage/managerwidget.cpp managerpage/managerwidget.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o managerwidget.o managerpage/managerwidget.cpp

pkupdates.o: updatepage/pkupdates.cpp updatepage/pkupdates.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pkupdates.o updatepage/pkupdates.cpp

updatepage.o: updatepage/updatepage.cpp updatepage/updatepage.h \
		updatepage/taskbar.h \
		updatepage/appwidget.h \
		updatepage/funcwidget.h \
		updatepage/pkupdates.h \
		jsonfunc.h \
		sharedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o updatepage.o updatepage/updatepage.cpp

jsonfunc.o: jsonfunc.cpp jsonfunc.h \
		sharedata.h \
		qreplytimeout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsonfunc.o jsonfunc.cpp

guifactory.o: guifactory.cpp guifactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guifactory.o guifactory.cpp

commentlistmodel.o: commentlistmodel.cpp commentlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commentlistmodel.o commentlistmodel.cpp

homeimglistmodel.o: homeimglistmodel.cpp homeimglistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homeimglistmodel.o homeimglistmodel.cpp

detailimglistmodel.o: detailimglistmodel.cpp detailimglistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detailimglistmodel.o detailimglistmodel.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

moc_softwarecenterwindow.o: moc_softwarecenterwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_softwarecenterwindow.o moc_softwarecenterwindow.cpp

moc_homewidget.o: moc_homewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homewidget.o moc_homewidget.cpp

moc_titlebar.o: moc_titlebar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_titlebar.o moc_titlebar.cpp

moc_classtop.o: moc_classtop.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classtop.o moc_classtop.cpp

moc_classwidget.o: moc_classwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classwidget.o moc_classwidget.cpp

moc_element.o: moc_element.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_element.o moc_element.cpp

moc_showmore.o: moc_showmore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_showmore.o moc_showmore.cpp

moc_appwidget.o: moc_appwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appwidget.o moc_appwidget.cpp

moc_funcwidget.o: moc_funcwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_funcwidget.o moc_funcwidget.cpp

moc_taskbar.o: moc_taskbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskbar.o moc_taskbar.cpp

moc_detailwidget.o: moc_detailwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detailwidget.o moc_detailwidget.cpp

moc_customlineedit.o: moc_customlineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customlineedit.o moc_customlineedit.cpp

moc_searchwidget.o: moc_searchwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchwidget.o moc_searchwidget.cpp

moc_datamanager.o: moc_datamanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datamanager.o moc_datamanager.cpp

moc_imgwindow.o: moc_imgwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgwindow.o moc_imgwindow.cpp

moc_classpage.o: moc_classpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_classpage.o moc_classpage.cpp

moc_morepage.o: moc_morepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_morepage.o moc_morepage.cpp

moc_recommendwidget.o: moc_recommendwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recommendwidget.o moc_recommendwidget.cpp

moc_managerpage.o: moc_managerpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managerpage.o moc_managerpage.cpp

moc_managerwidget.o: moc_managerwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_managerwidget.o moc_managerwidget.cpp

moc_pkupdates.o: moc_pkupdates.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pkupdates.o moc_pkupdates.cpp

moc_updatepage.o: moc_updatepage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_updatepage.o moc_updatepage.cpp

moc_jsonfunc.o: moc_jsonfunc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jsonfunc.o moc_jsonfunc.cpp

moc_qreplytimeout.o: moc_qreplytimeout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qreplytimeout.o moc_qreplytimeout.cpp

moc_guifactory.o: moc_guifactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guifactory.o moc_guifactory.cpp

moc_commentlistmodel.o: moc_commentlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commentlistmodel.o moc_commentlistmodel.cpp

moc_homeimglistmodel.o: moc_homeimglistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homeimglistmodel.o moc_homeimglistmodel.cpp

moc_detailimglistmodel.o: moc_detailimglistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detailimglistmodel.o moc_detailimglistmodel.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

